// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAne8fTHayvtRNo0dIDojuqO1IFc01VKGk',
    appId: '1:202299967647:web:5e3b3602e87e3bc7617aaa',
    messagingSenderId: '202299967647',
    projectId: 'foodexpressappcrd',
    authDomain: 'foodexpressappcrd.firebaseapp.com',
    storageBucket: 'foodexpressappcrd.appspot.com',
    measurementId: 'G-5QSPN1R92S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOUdVNUHjEeKD1UdL-jx0iwh1YJFCo3Ic',
    appId: '1:202299967647:android:d86499bf1cc57ce6617aaa',
    messagingSenderId: '202299967647',
    projectId: 'foodexpressappcrd',
    storageBucket: 'foodexpressappcrd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUIKPm10NMs96VPy3w3cTDIYuy1VV0U5I',
    appId: '1:202299967647:ios:e3471dc086f9fa59617aaa',
    messagingSenderId: '202299967647',
    projectId: 'foodexpressappcrd',
    storageBucket: 'foodexpressappcrd.appspot.com',
    iosBundleId: 'com.example.foodexpress',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUIKPm10NMs96VPy3w3cTDIYuy1VV0U5I',
    appId: '1:202299967647:ios:e3471dc086f9fa59617aaa',
    messagingSenderId: '202299967647',
    projectId: 'foodexpressappcrd',
    storageBucket: 'foodexpressappcrd.appspot.com',
    iosBundleId: 'com.example.foodexpress',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAne8fTHayvtRNo0dIDojuqO1IFc01VKGk',
    appId: '1:202299967647:web:542fe0d7a1dc1348617aaa',
    messagingSenderId: '202299967647',
    projectId: 'foodexpressappcrd',
    authDomain: 'foodexpressappcrd.firebaseapp.com',
    storageBucket: 'foodexpressappcrd.appspot.com',
    measurementId: 'G-00JNVE2SBL',
  );
}
